name: gem

on:
  workflow_dispatch:
    inputs:
      rubygems-otp-code:
        description: RubyGems OTP code
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # actions/checkout@7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Ruby
        # ruby/setup-ruby v1.321.0
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          bundler-cache: true
      - run: bundle install

      - name: Setup git config
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_NAME }}

      - name: git
        run: |
          git status
          git diff

      - name: Publish to RubyGems
        run: bundle exec rake release --trace
    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      GEM_HOST_OTP_CODE: ${{ github.event.inputs.rubygems-otp-code }}
